version: '2'
services:
    fauxshop-app:
        image: fauxshop
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fauxshop-mysql:3306/fauxshop?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fauxshop-mysql:
        extends:
            file: mysql.yml
            service: fauxshop-mysql
